# PBS flags
queue: express
project: e14
walltime: 00:30:00
ncpus: 1
mem: 2GB
jobname: MOM_Gyre


# Model config
model: mom
shortpath: /scratch/e14
exe: fms_MOM_solo.x
input:
     - mom_ra
collate: true
restart_freq: 1

collate:
  walltime: 0:05:00
  mem: 2GB
  ncpus: 1
  queue: express
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

storage:
        gdata:
                - ik11

# Misc
stacksize: unlimited
mpirun: --mca mtl mxm
qsub_flags: -lother=hyperthread
