# PBS flags
queue: express
project: e14
walltime: 04:00:00
ncpus: 32
mem: 32GB
jobname: MOM_Gyre


# Model config
model: mom
shortpath: /scratch/e14
exe: fms_MOM_solo_lapt.x
input:
     - gyre1_0166
collate: true
restart_freq: 1

collate:
  walltime: 0:30:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

storage:
        gdata:
                - ik11

# Misc
stacksize: unlimited
mpirun: --mca mtl mxm
qsub_flags: -lother=hyperthread
