# PBS flags
queue: express
project: e14
walltime: 03:00:00
ncpus: 8
mem: 16GB
jobname: MOM_Gyre


# Model config
model: mom
shortpath: /scratch/e14
exe: fms_MOM_solo.x
input:
     - gyre1
collate: true
restart_freq: 1

collate:
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

# Misc
stacksize: unlimited
mpirun: --mca mtl mxm
qsub_flags: -lother=hyperthread
