format: yamanifest
version: 1.0
---
work/INPUT/grid_spec.nc:
  fullpath: /scratch/e14/rmh561/mom/input/mom_ra/grid_spec.nc
  hashes:
    binhash: a14f8e230d06bc735a490bcb53ad6505
    md5: 689031464724f87aa5cd6dd06353585f
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/input/mom_ra/ocean_temp_salt.res.nc
  hashes:
    binhash: db5ee05dbf15d4220cec9cf6a11a6e37
    md5: 5e1e9483435059fc672ff863dc98fae8
work/INPUT/ocean_temp_salt_res_momgyre.nc:
  fullpath: /scratch/e14/rmh561/mom/input/mom_ra/ocean_temp_salt_res_momgyre.nc
  hashes:
    binhash: 1df248bf69ae9a49f0d955f4d394381f
    md5: 8bcd93fc89b366cf4a954c7acde06ba9
work/INPUT/salt_sfc_restore_MOM025.nc:
  fullpath: /scratch/e14/rmh561/mom/input/mom_ra/salt_sfc_restore_MOM025.nc
  hashes:
    binhash: 8c85688813fa58d866d372e2a782a2a0
    md5: 03b22565aee5aabc37e8b599d2ae6f08
work/INPUT/tau.nc:
  fullpath: /scratch/e14/rmh561/mom/input/mom_ra/tau.nc
  hashes:
    binhash: d3d0d16ebddc40a0443007ace64c77e5
    md5: ffffcca8c32b77b958c03fe9c2f98b68
work/INPUT/temp_sfc_restore.nc:
  fullpath: /scratch/e14/rmh561/mom/input/mom_ra/temp_sfc_restore.nc
  hashes:
    binhash: 9b0dd154389ae989c76e163fcb41bd09
    md5: 35b79705f17ba135dad51ed6376f25fc
