format: yamanifest
version: 1.0
---
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_barotropic.res.nc
  hashes:
    binhash: 7a7f21fc812c7bbcd84d53cad6ef2a78
    md5: 0dc0a3608b8896d1560e81bfe9169161
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_bih_friction.res.nc
  hashes:
    binhash: 4cf50314058c1c24aafda7774cc3c9bd
    md5: 8290c81b712202bd8691c75923788bbd
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_con_temp.res.nc
  hashes:
    binhash: cca73667aac57db26de3592f2e7615ff
    md5: a1d7dbfb42eb7e8417c1b305d1038df7
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_density.res.nc
  hashes:
    binhash: 7aae154ceda1c978394289ceb1cf73e4
    md5: 7cbc9d72419e23d2bb576e3fc7f642fc
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_sbc.res.nc
  hashes:
    binhash: a9f1f02f9880771d642a459b5452b6a9
    md5: 8ceb47b719737672490b92c54bd661e1
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_solo.res
  hashes:
    binhash: 39ec72ed6e260cc9f17a663c65078c1a
    md5: 3b1323b3d2b859806d294d96c3eaaff7
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_temp_salt.res.nc
  hashes:
    binhash: dd9c54ac2cfaf1701d82542b6d0b01c3
    md5: 8c0ec56bbac58e14b1ab8e18a1c65522
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_thickness.res.nc
  hashes:
    binhash: 9703fda30334afdcecc4e9892f880449
    md5: 1b388ddda9d5389d0803800b31c53aea
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_tracer.res
  hashes:
    binhash: a55df5d6829396605c557e7f39183ffa
    md5: 6be8c51a6fc6b63e1cf4a9c553a2ba41
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_velocity.res.nc
  hashes:
    binhash: 62260afb125736e4d30875cc42e6ebb5
    md5: 42dafccf49a75dfbccee8ff3ff3ba141
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart007/ocean_velocity_advection.res.nc
  hashes:
    binhash: e97770f832e91aa1a4db6bd01db2f7cd
    md5: eb3f3de6981ed9f2769fd426b6e78f73
