format: yamanifest
version: 1.0
---
work/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_age.res.nc
  hashes:
    binhash: 2052d4e260556e10d5d162f64f1e74e8
    md5: 885d5b758ad2b4c38d47722ddfb573ac
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_barotropic.res.nc
  hashes:
    binhash: b3402a5a509194ec2ee75030f2bdab84
    md5: 9fa6d92a92dce7eab4a9dcaa37085701
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_bih_friction.res.nc
  hashes:
    binhash: e8201c3b07a338f9e63b9f74d98ffe50
    md5: 847126b9720d4d8b71aef57bbfd61ad5
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_con_temp.res.nc
  hashes:
    binhash: 3b9a9d1844162134d56defbb71a56b75
    md5: 09e1cf702d8331ac3c88722aca386c6a
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_density.res.nc
  hashes:
    binhash: 2e98a342348fa6c13dd7c4f2a31e30a9
    md5: 25d4e4a75eb26975f2143db39447255a
work/INPUT/ocean_psom_moments.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_psom_moments.res.nc
  hashes:
    binhash: 5485abc53dc15b34bedebf057e212ad6
    md5: ed45e0e9ee11d913ae236d86b5319e5c
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_sbc.res.nc
  hashes:
    binhash: ce59659e99e880f8862ddc3ca59f44d1
    md5: 335fdf0526791606f18f76d923a4dd37
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_solo.res
  hashes:
    binhash: 80e857b0d34b940b82f626373a96bec8
    md5: 7fd971602c16007d7638c1340636fd3e
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_temp_salt.res.nc
  hashes:
    binhash: c8e0963f114a4a55f40be1198e7abe5a
    md5: bf19e70e83ed1d8cb92221e722ee6c01
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_thickness.res.nc
  hashes:
    binhash: d66026f3ddb537bddcd6d612ef305919
    md5: 1530e1eaed6a120ba1be2a5062f97e52
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_tracer.res
  hashes:
    binhash: 3abc5046b5d71851d9138d2a90e089d2
    md5: d7c1d179f984a8edb85d0b04160a7831
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_velocity.res.nc
  hashes:
    binhash: 1b9e106a00a62a3be395739530eabd4a
    md5: f89f58cb6b6462ddc5a7fecf94f888bc
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_velocity_advection.res.nc
  hashes:
    binhash: b31291e687705791c2b9c30b7ec084d2
    md5: 52ff718fbad94bb544f91262fbd8c292
