format: yamanifest
version: 1.0
---
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_barotropic.res.nc
  hashes:
    binhash: 8e63491412c67c5795ebdb65dbd79e48
    md5: 8a18550a0fa445d4a3bb1c2363d3a20c
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_bih_friction.res.nc
  hashes:
    binhash: a1d802ddfbd2ee0d0e1013bb25376cbd
    md5: 5a7b960e82860526b51eaf6224e55eea
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_con_temp.res.nc
  hashes:
    binhash: 0b787d71fea48956d9ddd99248a676bc
    md5: a9195f14b29c61a8b1db408bc9159fc8
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_density.res.nc
  hashes:
    binhash: 2e12acacd4a58d8b5f379b46a900728e
    md5: f0168f8b3b156739beecad1af287283c
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_sbc.res.nc
  hashes:
    binhash: 15e2cea24723842cad6539c8cd3ee08d
    md5: b0dd8be21c7e88ec7b223c6a9f8b0608
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_solo.res
  hashes:
    binhash: da52a90c3e7bac09175f232e6543554c
    md5: ff767584183ec2eb61913abd3b77c9f1
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_temp_salt.res.nc
  hashes:
    binhash: bb13fd7a2fc5a4a24a81c06e0213aa16
    md5: a393c587980f830c814eb4e0b3325831
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_thickness.res.nc
  hashes:
    binhash: b04d1708b619ebc787c52b92962322e8
    md5: 05e9e07cd0566ba5e94a29395c90736e
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_tracer.res
  hashes:
    binhash: e3605d1af9e440f8a39512a85024fb6f
    md5: 401b45b4a7ad8aeda16109d3bd04c775
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_velocity.res.nc
  hashes:
    binhash: 987bcb8a67efa605649163ab846c8305
    md5: 500e47e9337611a67796f1a6d9ec53a8
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart010/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3f7442e3875ddfd767edffb4250d47e1
    md5: e59b1ab84595bfa11f32cbd784e5faaa
