format: yamanifest
version: 1.0
---
work/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_age.res.nc
  hashes:
    binhash: fe5e4ed8d6daa0efe1e184b08a989b78
    md5: 93a11a554bffedb29a913028416a8043
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_barotropic.res.nc
  hashes:
    binhash: 5a68445d4a839746683148003feeb4e9
    md5: 19391bc04476a29caf41e0f8cf64bc6a
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_bih_friction.res.nc
  hashes:
    binhash: 19eec78975f92a8a6d2e6c99f78218d5
    md5: 47bde22323d4d711d01873114216d98f
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_con_temp.res.nc
  hashes:
    binhash: 69296d4e57f0e08acb4721a13d048c49
    md5: 958966f64b8ad8db2375239ddcb91c70
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_density.res.nc
  hashes:
    binhash: 53076c6d059fa3285a16f8a9fb6330be
    md5: 20660fc02b5a0b6039e344a2477f7ad5
work/INPUT/ocean_psom_moments.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_psom_moments.res.nc
  hashes:
    binhash: 26127aa0699d3f0af3cfcda233662df2
    md5: 71c52f5f435964df117ebc662dbd4a97
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_sbc.res.nc
  hashes:
    binhash: 53a20531c0ce3ccc87add3a8f3cc3250
    md5: d0c2efcc5e85b58261895bb326f1e6fe
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_solo.res
  hashes:
    binhash: d272841f2e1543e6b46107a3b260474a
    md5: 317c035dbc08223412804f94014c05e9
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_temp_salt.res.nc
  hashes:
    binhash: ed46c4f0256c0df5a26e984f0bd7e3c0
    md5: 1390c15af63d8234046e9cea8d76fd7a
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_thickness.res.nc
  hashes:
    binhash: d78fa4a53d0540a2b31c83ec801cbef7
    md5: 03a327cf02a27a7eb8f03ef7bb631c6b
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_tracer.res
  hashes:
    binhash: a6aa1eb47b6ac8b81e5954efb6749e59
    md5: 73f0a7ab0e293cadce1d846dc6141c12
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_velocity.res.nc
  hashes:
    binhash: 720a04da1eb88576b8cf67087a87409e
    md5: 1a4c07c476242657cbbae5eebe6fa243
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_velocity_advection.res.nc
  hashes:
    binhash: 51c3053b6e3d16c653052fd55b997c84
    md5: 401d6437b63cb8f07fbdf44377f58247
