format: yamanifest
version: 1.0
---
work/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_age.res.nc
  hashes:
    binhash: f9eb311c3e746e969cd67f18a9baab42
    md5: c9b561fb596fd32078d72af184f70ebb
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_barotropic.res.nc
  hashes:
    binhash: a55a0632afce03cccf537ee5069023c2
    md5: a5de7f526c81ae1b52318ecbfdca6f95
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_bih_friction.res.nc
  hashes:
    binhash: a98abb5710f24ef829517510573ce2f5
    md5: ecde9f1acdf505867842e577ca6fd25a
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_con_temp.res.nc
  hashes:
    binhash: fecca46352d63b564dda35db3cd5d662
    md5: 8230a8f6fca16cff2dd009c7a2748ffa
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_density.res.nc
  hashes:
    binhash: 5ae8d02a8d64c3b92cbe8e3899752196
    md5: 7465c4e6606e506f57dba42b77f75843
work/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_neutral.res.nc
  hashes:
    binhash: cdb221c3f0bece33c25ed10034edf0f4
    md5: a7cec2ec94bef47463ab89ad1c4305ce
work/INPUT/ocean_psom_moments.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_psom_moments.res.nc
  hashes:
    binhash: f0cce1073cf49d9967f5d9401ee7b296
    md5: c117b2189b332d33457b36d21ab72a62
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_sbc.res.nc
  hashes:
    binhash: 7e41981f58f9a467a4dd091764bc3264
    md5: 1cabf4d6f3ed42639bab7305530f0cb7
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_solo.res
  hashes:
    binhash: 4160a8a4bc55884d18432ff7feebfa2c
    md5: e7d7fd6cdcbf5bae5f0f1a5e10706df2
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_temp_salt.res.nc
  hashes:
    binhash: 6a090aebc52eb623bddcdb489f2dfaa1
    md5: 628f39c38899336f34582456cf7b6cbf
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_thickness.res.nc
  hashes:
    binhash: 186e150efa2f99a5ea8cdbc2361ece04
    md5: 70337f70bc8b2c52a8a360add1ef8b73
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_tracer.res
  hashes:
    binhash: 2b6400e614e64ec4115c4fb5c043bf17
    md5: 5f75e882091fc25c023fd24fae60a68a
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_velocity.res.nc
  hashes:
    binhash: 56ecef2f0efc17772913af9d0cca76eb
    md5: e4b96aa9e41a2e577a10d2b4557cf3b7
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart001/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5d65824e7420be4f9d3d08bd1e15dc98
    md5: 4f33666ab4365d390f257d1d50ef12d3
