format: yamanifest
version: 1.0
---
work/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_age.res.nc
  hashes:
    binhash: 94ca4c0ec497b236c1584791f54ed30e
    md5: fb00f9d5c16b45448c03dd6ff4f13b3f
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_barotropic.res.nc
  hashes:
    binhash: 379ad6709844c14d55795b6a065bcd9d
    md5: eaa3f17ea6aa7a5f8704229c77c5f846
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_bih_friction.res.nc
  hashes:
    binhash: 146fe76666c9177406c1b6c37b7749a3
    md5: 99d9753e74f1cb20cb67319633b50444
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_con_temp.res.nc
  hashes:
    binhash: 9c229ab5f0e5a15fd8e69c16b2384c0a
    md5: 8a9355c94556309ba7977274cc74a910
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_density.res.nc
  hashes:
    binhash: 48e7d390e80290145745307af40163e2
    md5: b86bb7ea48167f7b98ec1bfec95f8397
work/INPUT/ocean_psom_moments.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_psom_moments.res.nc
  hashes:
    binhash: a79f66e25f86c8a278ba30d414f9edbe
    md5: 8a8ac23fba92ff531973f1854f119897
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_sbc.res.nc
  hashes:
    binhash: 6e0e6a0fc7cf368166343f1f6ed5d09f
    md5: 1be994182d0a14b7c6e5a7676475f673
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_solo.res
  hashes:
    binhash: 78b7a5e4dbba18c33e55f1c22679a7d2
    md5: 7fd971602c16007d7638c1340636fd3e
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_temp_salt.res.nc
  hashes:
    binhash: 9eea694141ede90888a7b563752bdc4e
    md5: 58077aff7b86b8afa6f9076b2b6b2168
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_thickness.res.nc
  hashes:
    binhash: f5dc1b223152960991559d2a0ca21418
    md5: cd19fa6514a909755b12595796020fa3
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_tracer.res
  hashes:
    binhash: d11271ce30015c3554c0b9b942713b20
    md5: 36027ad4f6d02ea436e710c690c5babb
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_velocity.res.nc
  hashes:
    binhash: daf0bf86f04c1831ed1d21577695a28d
    md5: 0c34a929d67ae2486269b38031533ef7
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart004/ocean_velocity_advection.res.nc
  hashes:
    binhash: c690095315491239857895ad4cf54fde
    md5: 80d56ff491e0b55b9a14b003a542029a
