format: yamanifest
version: 1.0
---
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_barotropic.res.nc
  hashes:
    binhash: e23da75e4252c1c421ba6f50fdd655e7
    md5: 6d86c5fdad7eb365a62fa7fa229d0ce1
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_bih_friction.res.nc
  hashes:
    binhash: 98bff8c994c4d04f71d6cfc08c30fec1
    md5: db62b670d7c659c9f0ea8a371d7a1083
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_con_temp.res.nc
  hashes:
    binhash: d7771842999320a265ba9408cfe183db
    md5: c608306b0913b26e80f149a92e6fd9ca
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_density.res.nc
  hashes:
    binhash: 1d0b8b17714993dbe9842738132ce132
    md5: a18c05189a564c55e77abca9cd87d3f9
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_sbc.res.nc
  hashes:
    binhash: f51ee2cbe782915c4cb17cf6063dc5f1
    md5: 66cb5827501c8c74f4e006c8d1833ca6
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_solo.res
  hashes:
    binhash: 2dc4ab5709ddbeaab7b968f2d168eb37
    md5: 7fd971602c16007d7638c1340636fd3e
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_temp_salt.res.nc
  hashes:
    binhash: a278fb0aff2d7587a0b5df295dd03ac9
    md5: e6434980ba20dcf169db259e3cd2fa74
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_thickness.res.nc
  hashes:
    binhash: 0c0e6054b7860e043e33a0e02bb177bd
    md5: acf6a6ff96fcb663bcb8fd549d0e2935
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_tracer.res
  hashes:
    binhash: b4c29143d97684df68e367f250486899
    md5: f3548702b58d01ba3a56ea60a636d924
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_velocity.res.nc
  hashes:
    binhash: 90d81631f7063ecb6d8a22f5faef2216
    md5: 84d981971758f8c500aef416f9baf006
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart004/ocean_velocity_advection.res.nc
  hashes:
    binhash: e2d2bdbd83be614b2ad784414391cbd4
    md5: 83e4200a8a2ab0106dfd397a79c39de1
