format: yamanifest
version: 1.0
---
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_barotropic.res.nc
  hashes:
    binhash: 3915435d5b2f9c76e15875597da10e85
    md5: 554938285b312274ba54ec3b35922aa2
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_bih_friction.res.nc
  hashes:
    binhash: 8b39481e168b43f7fb346e71ebc8b8eb
    md5: bc2e16cad1a07f5535e4a77d05205da6
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_con_temp.res.nc
  hashes:
    binhash: fe2df09a92b7d7e213ffc4a6d5422b32
    md5: 0592ad9b4abc7dcea9309ed77c03732f
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_density.res.nc
  hashes:
    binhash: dcc56726f3bca595098a5618dbdbe779
    md5: eaf3ed7ea05bbd31e67bbceab2ce8126
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_sbc.res.nc
  hashes:
    binhash: e71ceec364c14f692762f62b6b19c55f
    md5: a380acdd9549c241fc97a95eef39eeb5
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_solo.res
  hashes:
    binhash: 90c5ac04aa510b9bd1e7b6eddb2b1da0
    md5: 45b3d6f3c104186916e0c5c5d22ec778
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_temp_salt.res.nc
  hashes:
    binhash: 74adf51ef30f5692dcfeb76941a3a324
    md5: faecf40e92f6e3e1c20743016e4fd1c9
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_thickness.res.nc
  hashes:
    binhash: c8b4f490745d256ad95f1fb3ce949f6e
    md5: 75896ed11033658e514ad0660abfecc9
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_tracer.res
  hashes:
    binhash: 5b97a06806d837515be4acb4ea3ddbf7
    md5: b116ebc7c46e5205fd92c5e7157e1f08
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_velocity.res.nc
  hashes:
    binhash: 14cb107e984247c9dfbbfb485f148e4e
    md5: 60d5d234a41dc238ab6083e23cf9da2a
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart008/ocean_velocity_advection.res.nc
  hashes:
    binhash: 137c915caef346f9ddb3f7843571e11f
    md5: f73e98961abfbe51d774dd9fa8468090
