format: yamanifest
version: 1.0
---
work/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_age.res.nc
  hashes:
    binhash: 7e2a9bdc9851e05bc919ab7cd16686e5
    md5: 7197120d553d8ff7f4746bced97a30f3
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_barotropic.res.nc
  hashes:
    binhash: 57746ba0933edd2686d5c8b2d1204827
    md5: ef9e3e1b7d719ba8715c51a82e1f9246
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_bih_friction.res.nc
  hashes:
    binhash: 9510f01053dedf16d7428595456e1131
    md5: d1ec3d316f482c1f53a16c9ce07c6949
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_con_temp.res.nc
  hashes:
    binhash: a33e0ea65d34dcb7b9114c90990a4964
    md5: f0cda2e019f74332498ef88264d139c0
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_density.res.nc
  hashes:
    binhash: f04b0d447559bb8b7d66a0bc181a11b8
    md5: b5440c7a72c0631cd0e7b1aeaf52284a
work/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_neutral.res.nc
  hashes:
    binhash: c25b73f0b75ad109b5c1c88d8aa4dfce
    md5: 651f617fbfc427d43510158ad6b65a9f
work/INPUT/ocean_psom_moments.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_psom_moments.res.nc
  hashes:
    binhash: c9227d398f42dd909d0c3ee774c58fca
    md5: 54295ed0ce782b84ae1d465729b3ea7a
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_sbc.res.nc
  hashes:
    binhash: e4847d42f1149835e82141baa5512bbe
    md5: cdb8f091534b8e2fa31e2171cadf39df
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_solo.res
  hashes:
    binhash: 3d0dcb1027262a447ff8b5ba44468001
    md5: 317c035dbc08223412804f94014c05e9
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_temp_salt.res.nc
  hashes:
    binhash: ea3d7d25dd67e8233dcba55aafb13a0a
    md5: 510b3ae5957ae86229cf213c0e37b535
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_thickness.res.nc
  hashes:
    binhash: 39477444069c15e995e6127cbf401419
    md5: 4dfe2c6ab587d7e132053d96be7667ae
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_tracer.res
  hashes:
    binhash: 607d15aec80b1283ce8121bca9d95b49
    md5: cb9136d150e13c1fc75e24ccf661113d
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_velocity.res.nc
  hashes:
    binhash: cd9f042915c76f4daeed81036c1352f7
    md5: 2b83ee4f3763ed325de09a3bd2b5ed18
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart000/ocean_velocity_advection.res.nc
  hashes:
    binhash: b115c8177546ddfdc7a8c91416ba9f81
    md5: 8fe0708cc34b784199af71d75c4cbd62
