format: yamanifest
version: 1.0
---
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_barotropic.res.nc
  hashes:
    binhash: 001a5fa969bd649970679f0a4f3692c3
    md5: 47a006eeacde8cdd33cfb3e6b33143c3
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_bih_friction.res.nc
  hashes:
    binhash: c76c0b949f00e1f68375c5385d14c38f
    md5: c9c74cb7441fe1ff24c77ebe0b1f4fec
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_con_temp.res.nc
  hashes:
    binhash: 24358cdfb9f54a9d681c539c16736971
    md5: 42ed9eb84311bec772488b4006b6f8f5
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_density.res.nc
  hashes:
    binhash: b483163a55663cf19cbf98fd0a271e4b
    md5: ebab1e068fd58562c5f78e44edf9b834
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_sbc.res.nc
  hashes:
    binhash: ce098fc92d2f2749203d20474e498cdf
    md5: 268613dee5a7e42682cdcd1b8fd31007
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_solo.res
  hashes:
    binhash: db1ab07c9f9144a842b4ba1ce37bb01f
    md5: 43c56765df2939db104c1e902851af4d
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_temp_salt.res.nc
  hashes:
    binhash: 6c943fba3dd6c39493cace9cd7b0fe41
    md5: 81b2272f4dcff63575cfb64275bc5df7
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_thickness.res.nc
  hashes:
    binhash: 853a3b9b203428c896a0690b4e711b53
    md5: 126d9483dcecba776ec274b0075f1676
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_tracer.res
  hashes:
    binhash: 99b4c44bb00d00222ddf5f85dce6e711
    md5: 970844167bf822e8cf18708445034f7a
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_velocity.res.nc
  hashes:
    binhash: f9323e046c59306afc02f333227783b9
    md5: d0b77ce69ca5dc528c741a057cb64a34
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart016/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5d81ee1705554416baeb8b024e9f7e32
    md5: 3fb4b581fff266e2435eb05067fd2e5a
