format: yamanifest
version: 1.0
---
work/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_age.res.nc
  hashes:
    binhash: e83c8395aaa773b49584857f42692de8
    md5: d1c909de74ab9b5b490a0340a39ad1f9
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_barotropic.res.nc
  hashes:
    binhash: 7394ad4ef0fcff3fb15834de2cd8fea5
    md5: 49c2beb26c597d5c7d002b1ee92b7fc0
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_bih_friction.res.nc
  hashes:
    binhash: 05e8d0175100970cd3d11f38f795fce9
    md5: 7abedf96b020d26f9e181cc479ba8876
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_con_temp.res.nc
  hashes:
    binhash: a7e79c885d71a827c088c64b47741656
    md5: 8845261509a1f92ee2ab6c446d507d68
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_density.res.nc
  hashes:
    binhash: 8d8f0ec6dc3aaa83315cefb31ad14276
    md5: db38f9f6d42330a43ebe514485a53337
work/INPUT/ocean_psom_moments.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_psom_moments.res.nc
  hashes:
    binhash: f3170a2b54e7ce979c086296fabe82b8
    md5: f1fb59d56ad23c29da55bd9de203e045
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_sbc.res.nc
  hashes:
    binhash: 45c72ffec65e4caf9dbb0bbbde3665db
    md5: adda5a615e4a7910e37e3d8530dcfb6c
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_solo.res
  hashes:
    binhash: c093401a271d08395d0ae734200894ab
    md5: e0101c98b0247e5364a8b6f217c82fbc
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_temp_salt.res.nc
  hashes:
    binhash: 7b976736731c3e4d558df6bbbf6865c4
    md5: f25eb09825e237b2defd68ef3a577ad1
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_thickness.res.nc
  hashes:
    binhash: 89ca48fd57a0336cdc9acbbe641f90bd
    md5: fdce4a4b7155d96af7013ce9bb254ffe
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_tracer.res
  hashes:
    binhash: e57216f301e3c936d264f8d6c8481c1e
    md5: a3a03d1986749f578e5f5721f31832d7
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_velocity.res.nc
  hashes:
    binhash: abad5a11c9127bdeebe2e9758a7405fe
    md5: 9eb72990d1723c84575a0b8dae26d864
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre/restart002/ocean_velocity_advection.res.nc
  hashes:
    binhash: 48255775c64ad9a7ecfa2acf29d591a8
    md5: 25cecdb556ed6a832974a467b6abcb4b
