format: yamanifest
version: 1.0
---
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_barotropic.res.nc
  hashes:
    binhash: 88e81885b8f97f7b8ade63c6d0c4ca3b
    md5: c39ea307d653907160e5489d04ae1856
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_bih_friction.res.nc
  hashes:
    binhash: 1e084ccece8beb20784d958438ff40fc
    md5: de2c2a70888a0d7eb71a07864808fbed
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_con_temp.res.nc
  hashes:
    binhash: 9a2d637f7624e55e115bc60898d7e192
    md5: d50a4217150186daeb638df23877f637
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_density.res.nc
  hashes:
    binhash: 9331cd5ccbef456275e0f55ecc71f84e
    md5: 4d280fca44bd10da83792f57372644fa
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_sbc.res.nc
  hashes:
    binhash: e1e19b39e40f09bb7c7ad9dc53177097
    md5: 26be04b009782a7f45d1c1568f70cc7d
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_solo.res
  hashes:
    binhash: 4d30c1b59193e533e03fbe2f30836f67
    md5: da2c2dd65dc90c893b2d678dd8060d1a
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_temp_salt.res.nc
  hashes:
    binhash: 9820f8c4d64a17e7302c4e5db0368dd1
    md5: 2bec6202de19badeb024273a6788d7e7
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_thickness.res.nc
  hashes:
    binhash: b0fafa93dbdaba6f6bb0e414b1fe22a3
    md5: f7eb075dde511a27a77a506845c8bc55
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_tracer.res
  hashes:
    binhash: 16ccada8e9034a524779f2920abfb2ef
    md5: 311979663f0cd6fb201fe00b1b59b846
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_velocity.res.nc
  hashes:
    binhash: f165a6a9b1032e9a1152f9cffb7a3a3a
    md5: 96610ff2dc8f23c6c3681b9e1c7367d2
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart001/ocean_velocity_advection.res.nc
  hashes:
    binhash: 27f495d6e830f47dbd21f35cdbdd3fb0
    md5: 8ba263a96467e57f9588b7a1ad7d3f0a
