format: yamanifest
version: 1.0
---
work/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_barotropic.res.nc
  hashes:
    binhash: b1f0c904c531a998c6c68d765cede310
    md5: 38f68cec0418960392c263cc571fe342
work/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_bih_friction.res.nc
  hashes:
    binhash: ab3808cfe213773b1d77928fbf21751b
    md5: 2d1e5685bd15b9874995a0348cdcb4fc
work/INPUT/ocean_con_temp.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_con_temp.res.nc
  hashes:
    binhash: 9d6466a8ff3bf1c5d948d0f8e6852046
    md5: ab04ea65ae2bc578928f273e6824297f
work/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_density.res.nc
  hashes:
    binhash: 6208fc61b2e6c464066c1a3e34d7cacb
    md5: 8aa85025646e62c4235e8e4f4e9f816f
work/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_sbc.res.nc
  hashes:
    binhash: aceb9f9b043f0c7804dcab8b274cd61d
    md5: 92b2657b6e5a0ef478568c698464be6e
work/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_solo.res
  hashes:
    binhash: 1df2bc4b7f3e870fe6d64f9308df82bb
    md5: 053a9b2216c32854dccad9dd359557e7
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_temp_salt.res.nc
  hashes:
    binhash: cd3d073c426de486a2ea944cc6470d80
    md5: 104188cf548c4a4ebe2d777c882f4de8
work/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_thickness.res.nc
  hashes:
    binhash: e167fdb8f5336ab110b000fa14a9bea9
    md5: b490f8b5080f0e464bc423dfe041f5c1
work/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_tracer.res
  hashes:
    binhash: b7f02c43e8138474baa06c1f02e04bbe
    md5: 3ff07133a14019566cc644c35946f2f6
work/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_velocity.res.nc
  hashes:
    binhash: 9a0717f2bd941b6d26e3ab511457715e
    md5: 9e508858f64dba8a35db093c8ea44778
work/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/mom/archive/MOM_Gyre2/restart002/ocean_velocity_advection.res.nc
  hashes:
    binhash: 55de02d059bfdf94821b90a194708be8
    md5: 62d54d22204fc825b529d655dddd34d7
